apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: iri
  name: iri
spec:
  replicas: 1
  selector:
    matchLabels:
      name: iri
  template:
    metadata:
      labels:
        name: iri
    spec:
      containers:
      - image: iota-182418/kubeiri:0.0.3
        imagePullPolicy: IfNotPresent
        name: iri
        env:
        
        ports:
        - containerPort: 14777
          name: udp
          protocol: UDP
        - containerPort: 15777
          name: tcp
          protocol: TCP
        - containerPort: 14265
          name: api
          protocol: TCP
        volumeMounts:
        - mountPath: /iri/data
          name: iri-persistent-storage
      volumes:
      - hostPath:
          path: /data/iri
        name: iri-persistent-storage
---
apiVersion: v1
kind: Service
metadata:
  name: iri
  labels:
    app: iri
spec:
  ports:
    - port: 14777
    - port: 15777
    - port: 14265
  selector:
    app: iri
  type: ClusterIP
